comment: off
github_checks:
  annotations: false
coverage:
  status:
    patch:status:status:status:status:status:status:
      default:
        target: 95%
        only_pulls: true
    project:status:status:status:status:status:status:status:
      default:
        threshold: 1%
